language: r
os: linux
r: release
latex: false

warnings_are_errors: false

cache:
  packages: true

r_packages:
  - rmarkdown
  - knitr
  - bookdown
  - tidyverse
  - ggthemes
  - viridis
  - here
  - leaflet
  - sf
  - shiny
  - flexdashboard
  - thematic
  - DT
  - renv

script:
    - R -f R/_deploy.R