language: r
r: release
latex: false

warnings_are_errors: false

cache:
  packages: true

r_packages:
  - rmarkdown
  - knitr
  - bookdown
  - tidyverse
  - here
  - leaflet
  - shiny
  - flexdashboard

script:
    - R -f R/_deploy.R