dist: xenial
sudo: false
latex: false
language: r
r: release

warnings_are_errors: no

cache:
  packages: yes

apt_packages:
  - libgdal-dev
  - libudunits2-dev

git:
  depth: false

r_packages:
  - ggthemes
  - rsconnect
  - shiny
  - tidyverse
  - leaflet
  - flexdashboard

#script:
#  - R -f _deploy.R
