---
title: "Unfälle Regensburg"
output: 
  flexdashboard::flex_dashboard:
    theme:
      bootswatch: "journal"
      primary: "#008993"
    orientation: columns
    vertical_layout: fill
    source_code: embed
    fig_retina: 3
    fig_mobile: no
runtime: shiny
---

```{r global, include=FALSE}
library(flexdashboard)
library(shiny)
library(tidyverse)
library(leaflet)
library(sf)
library(DT)
library(viridis)

# plot theme
ggplot2::theme_set(
  ggthemes::theme_clean()
)

scale_fill_custom <- 
  viridis::scale_fill_viridis(
    discrete = TRUE,
    option = "D",
    direction = -1,
    end = 0.7
  )

# load data
load(
  here::here("data/regensburg_data.rda")
)

load(
  here::here("data/shapefiles.rda")
)


# common ----
bounds <- sf.regensburg |> st_bbox()

## marker ----
getMarkerColor <- function(data) {
  map(
    data$severity,
    function(x) {
      if (x == "Toedlich") {
        "red"
      } else if (x == "Schwer") {
        "orange"
      } else if (x == "Leicht") {
        "beige"
      }
    }
  )
}

```


```{r, include=FALSE}
# reactive data
filtered_data <- 
  reactive({
    
    res <-
      data |>
      filter(
        year %in% input$year_range[1]:input$year_range[2]
      )
    
    res <- 
      res |> 
      filter(
        severity %in% input$selected_severity
      )
    
    return(res)
  })
```


{.sidebar}
====

<h4>Filter</h4>

```{r}
# Define inputs
sliderInput(
  inputId = "year_range", 
  label = "Jahre", 
  min = min(data$year), 
  max(data$year), 
  value = c(min(data$year), max(data$year)),
  sep = "",
  ticks = FALSE
)

checkboxGroupInput(
  inputId = "selected_severity",
  label = "Schwere des Unfalls",
  choices = c(
    "Toedlich" = "Toedlich",
    "Schwere Verletzung" = "Schwer",
    "Leichte Verletzung" = "Leicht"
  ),
  selected = c(
    "Toedlich",
    "Schwer",
    "Leicht"
  ),
  inline = FALSE,
)
```

Author: [Konstantin Schneider](http://kdschneider.github.io/)



Wo/Wann/Wie
====

Spalte 1 {data-width=8}
----

###

```{r}
icons <- reactive({
  awesomeIcons(
    icon = 'ios-close',
    iconColor = 'black',
    library = 'ion',
    markerColor = getMarkerColor(filtered_data())
  )
})
```

```{r}
output$map1 <- 
  renderLeaflet({
    leaflet(
      data = filtered_data(),
      options = leafletOptions(
        crs = leafletCRS(code = "WGS84"),
        preferCanvas = NULL
      )
    ) |> 
    fitBounds(~min(lng), ~min(lat), ~max(lng), ~max(lat)) |> 
    setMaxBounds(~min(lng), ~min(lat), ~max(lng), ~max(lat)) |> 
    addProviderTiles(
      provider = providers$OpenStreetMap.DE,
      options = providerTileOptions(minZoom = 11)
    ) |> 
    # leafletProxy funktioniert nicht. die lösung hier ist nicht optimal. 
    # muss immer die gesamte karte neu rendern...
    addAwesomeMarkers(
      group = "Marker",
      lng = ~lng,
      lat = ~lat,
      clusterOptions = markerClusterOptions(),
      icon = icons()
    )
  })


leafletOutput("map1")
```

```{r}
absolutePanel(
  id = "controls",
  class = "panel panel-default",
  fixed = TRUE,
  draggable = TRUE,
  top = 75,
  left = 320,
  right = "auto",
  bottom = "auto",
  width = 180,
  height = "auto",

  selectInput(
    inputId = "fill",
    label = "",
    choices = c(
      "Schwere" = "severity",
      "Boden" = "street_condition",
      "Licht" = "light_condition"
    ), 
    selected = "Schwere"
  )
)
```



Spalte 2 {data-width=4}
----

### Monat

```{r}
output$monthly_plot <- 
  renderPlot({
    data <- filtered_data()
    
    data |> 
      mutate(
        month = as_factor(month) |> 
        fct_recode(
          "Jan" = "1",
          "Feb" = "2",
          "Mär" = "3",
          "Apr" = "4",
          "Mai" = "5",
          "Jun" = "6",
          "Jul" = "7",
          "Aug" = "8",
          "Sep" = "9",
          "Okt" = "10",
          "Nov" = "11",
          "Dez" = "12"
        ),
        severity = fct_infreq(severity) |> 
          fct_rev(),
        light_condition = fct_infreq(light_condition),
        street_condition = fct_infreq(street_condition)
      ) |> 
      count(month, .data[[input$fill]]) |> 
      ggplot(
        aes(x = month, y = n)
      ) +
      geom_col(
        aes_string(fill =  input$fill)
      ) +
      theme(
        legend.position = "top",
        legend.title = element_blank(),
        axis.title = element_blank()
      ) +
      scale_fill_custom
  })

plotOutput("monthly_plot")
```

### Wochentag

```{r}
output$weekday_plot <- 
  renderPlot({
    data <- filtered_data()
    
    data |> 
      count(weekday, .data[[input$fill]]) |> 
      ggplot(
        aes(x = weekday, y = n)
      ) +
      geom_col(
        aes_string(fill =  input$fill)
      ) +
      theme(
        legend.position = "top",
        legend.title = element_blank(),
        axis.title = element_blank()
      ) +
      scale_fill_custom
  })

plotOutput("weekday_plot")
```

### Uhrzeit

```{r}
output$hourly_plot <- 
  renderPlot({
    data <- filtered_data()
    
    data |> 
      count(hour, .data[[input$fill]]) |> 
      ggplot(
        aes(x = hour, y = n)
      ) +
      geom_col(
        aes_string(fill =  input$fill)
      ) +
      theme(
        legend.position = "top",
        legend.title = element_blank(),
        axis.title = element_blank()
      ) +
      scale_x_continuous(
        labels = function(x) {
          glue::glue("{x}:00 Uhr")
        }
      ) +
      scale_fill_custom
  })

plotOutput("hourly_plot")
```


Stadtteile
====

Spalte 1
----

###

```{r}
# district data
filtered_districts <- reactive({
  res <- 
    filtered_data() |> 
    st_as_sf(coords = c("lng", "lat"), crs = "WGS84") |> 
    rename(
      points = geometry
    ) |> 
    st_join(
      y = sf.districts |> rename("district_shape" = geometry),
      join = st_within,
      left = TRUE
    ) |> 
    select(-m2) |> 
    as_tibble() |> 
    left_join(
      y = sf.districts |> rename("district_polygon" = geometry) ,
      by = "district"
    ) |>
    drop_na(district) |>
    mutate(
      district = as_factor(district) |>
        fct_infreq() |>
        fct_rev()
    ) |> 
    add_count(district) |> 
    select(district, district_polygon, n, m2) |> 
    unique()
  
  if (input$selected_scale == "absolute") {
    res <- 
      res |> 
      st_as_sf()
  }

  if (input$selected_scale == "norm") {
    res <-
      res |> 
      mutate(
        n = n/max(res$n)
      ) |> 
      st_as_sf()
  }  
  
  if (input$selected_scale == "relative") {
    res <-
      res |> 
      mutate(
        n = n/max(cumsum(res$n))
      ) |> 
      st_as_sf()
  }
  
  if (input$selected_scale == "qkm") {
    res <- 
      res |> 
      mutate(
        n = round(n/m2 * 10^6)
      ) |> 
      st_as_sf()
  }
  
  return(res)
})

labels <- function(data) {
  glue::glue(
    "{data$district}: {round(data$n, digits = 2)}"
  )
}


output$map2 <- 
  renderLeaflet({
    leaflet(
    data = filtered_data(),
    options = leafletOptions(
      crs = leafletCRS(code = "WGS84"),
      preferCanvas = NULL
    )
  ) |> 
  fitBounds(~min(lng), ~min(lat), ~max(lng), ~max(lat)) |> 
  setMaxBounds(~min(lng), ~min(lat), ~max(lng), ~max(lat)) |>
    addProviderTiles(
      provider = providers$Stamen.TonerBackground,
      group = "Stadtteile",
      options = providerTileOptions(minZoom = 11)
    ) |> 
    addPolygons(
      data = filtered_districts(),
      group = "Stadtteile",
      opacity = 1,
      weight = 0.5, 
      fillOpacity = 0.8,
      color = "black",
      fillColor = ~colorNumeric("viridis", n)(n),
      highlightOptions = highlightOptions(
        color = "white", 
        weight = 2,
        bringToFront = TRUE
      ),
      label = labels(filtered_districts())
    )
  })


leafletOutput("map2")
```

```{r}
absolutePanel(
  id = "controls2",
  class = "panel panel-default",
  fixed = TRUE,
  draggable = TRUE,
  top = 75,
  left = 320,
  right = "auto",
  bottom = "auto",
  width = 180,
  height = "auto",

  selectInput(
    inputId = "selected_scale",
    label = "",
    choices = c(
      "Absolut" = "absolute",
      "Normiert" = "norm",
      "Relativ" = "relative",
      "Pro qkm" = "qkm"
    ), 
    selected = "Absolut"
  )
)
```

Spalte 2
----

### 

```{r}
output$district_plot <- renderPlot({
  plot <- 
    filtered_districts() |>
    ggplot(aes(x = district, y = n)) +
    geom_bar(
      aes(fill = n),
      stat = "identity"
    ) +
    scale_fill_viridis() +
    theme(
      axis.title = element_blank(),
      legend.title = element_blank(),
      panel.background = element_blank()
    ) +
    coord_flip()
  
  if (input$selected_scale == "relative") {
    plot <- 
      plot +
      scale_y_continuous(
        labels = scales::label_percent(accuracy = 1)
      )
  }
  
  return(plot)
})

plotOutput("district_plot")
```


Info
====

Über {data-width=350}
----

###

<h4>Über</h4>

Dieses Dashboard visualisiert Unfälle mit Personenschaden, die sich im Stadtgebiet Regensburg zugetragen haben. Die entstammen dem deutschlandweiten Unfallatlas des statistischen Bundesamts (LINK).

Es entstand als Teil meines Abschlussprojekts des Kurses "Daten Visualisieren" der Universität Regensburg. Der Rest des Projektes kann kann unter meiner [persönlichen Website](https://kdschneider.github.io/unfaelle-regensburg), bzw. auf [Github](https://github.com/kdschneider/unfaelle-regensburg), gefunden werden.

Daten {data-width=650}
----

###

<h4>Daten</h4>

```{r}
output$data_table <- DT::renderDataTable({
  filtered_data() |> 
    select(year:street_condition) |> 
    mutate(
      hour = glue::glue("{hour}:00 Uhr"),
      weekday = case_when(
        weekday == "Mon" ~ "Mo",
        weekday == "Tue" ~ "Di",
        weekday == "Wed" ~ "Mi",
        weekday == "Thu" ~ "Do",
        weekday == "Fri" ~ "Fr",
        weekday == "Sat" ~ "Sa",
        weekday == "Son" ~ "So"
      )
    ) |> 
    DT::datatable(
      colnames = c(
        "Jahr" = "year",
        "Monat" = "month",
        "Zeit" = "hour",
        "Tag" = "weekday",
        "Schwere" = "severity",
        "Licht" = "light_condition",
        "Boden" = "street_condition"
      )
    )
})

DT::dataTableOutput("data_table")
```

