---
title: "Unfälle Regensburg"
output: 
  flexdashboard::flex_dashboard:
    theme:
      bootswatch: "journal"
      bg: NULL
      fg: NULL
      primary: "#008993"
      secondary: NULL
      info: NULL
      warning: NULL
      danger: NULL
      base_font: NULL
      code_font: NULL
      heading_font: NULL
      font_scale: NULL
    orientation: columns
    vertical_layout: fill
    source_code: embed
    fig_retina: 3
    fig_mobile: yes
runtime: shiny
---

```{r global, include=FALSE, cache = TRUE}
library(flexdashboard)
library(shiny)
library(tidyverse)
library(leaflet)
library(sf)
library(DT)
library(viridis)

thematic::thematic_rmd(font = "auto")
# bslib::bs_themer()

load(
  here::here("data/regensburg_data.rda")
)

load(
  here::here("data/shapefiles.rda")
)


# map
bounds <- sf.regensburg |> st_bbox()
```


```{r, include=FALSE}
# reactive data
filtered_data <- 
  reactive({
    
    res <-
      data |>
      filter(
        year %in% input$year_range[1]:input$year_range[2]
      )
    
    res <- 
      res |> 
      filter(
        severity %in% input$selected_severity
      )
    
    return(res)
  })
```


Sidebar {.sidebar}
====

```{r}
# Define inputs
sliderInput(
  inputId = "year_range", 
  label = "Jahre", 
  min = min(data$year), 
  max(data$year), 
  value = c(min(data$year), max(data$year)),
  sep = "",
  ticks = FALSE
)

checkboxGroupInput(
  inputId = "selected_severity",
  label = "Schwere des Unfalls",
  choices = c(
    "Toedlich" = "Toedlich",
    "Schwere Verletzung" = "Schwer",
    "Leichte Verletzung" = "Leicht"
  ),
  selected = c(
    "Toedlich",
    "Schwer",
    "Leicht"
  ),
  inline = FALSE,
)
```

Author: [Konstantin Schneider](http://kdschneider.github.io/)



Wo/Wann/Wie
====

Spalte 1 {data-width=8}
----

###

```{r}
## markers ----
getMarkerColor <- function(data) {
  map(
    data$severity,
    function(x) {
      if (x == "Toedlich") {
        "red"
      } else if (x == "Schwer") {
        "orange"
      } else if (x == "Leicht") {
        "beige"
      }
    }
  )
}

icons <- reactive({
  awesomeIcons(
    icon = 'ios-close',
    iconColor = 'black',
    library = 'ion',
    markerColor = getMarkerColor(filtered_data())
  )
})
  
output$map1 <- 
  renderLeaflet({
    leaflet(
      data = filtered_data(),
      options = leafletOptions(
        crs = leafletCRS(code = "WGS84"),
        preferCanvas = NULL
      )
    ) |> 
    fitBounds(~min(lng), ~min(lat), ~max(lng), ~max(lat)) |> 
    setMaxBounds(~min(lng), ~min(lat), ~max(lng), ~max(lat)) |> 
    addProviderTiles(
      provider = providers$OpenStreetMap.DE,
      options = providerTileOptions(minZoom = 11)
    ) |> 
    # leafletProxy funktioniert nicht. die lösung hier ist nicht optimal. 
    # muss immer die gesamte karte neu rendern...
    addAwesomeMarkers(
      group = "Marker",
      lng = ~lng,
      lat = ~lat,
      clusterOptions = markerClusterOptions(),
      icon = icons()
    )
  })


leafletOutput("map1")
```

```{r}
absolutePanel(
  id = "controls",
  class = "panel panel-default",
  fixed = TRUE,
  draggable = TRUE,
  top = 75,
  left = 290,
  right = "auto",
  bottom = "auto",
  width = 180,
  height = "auto",

  selectInput(
    inputId = "fill",
    label = "",
    choices = c(
      "Schwere" = "severity",
      "Straßenverhältnisse" = "street_condition",
      "Lichtverhältnisse" = "light_condition"
    ), 
    selected = "Schwere"
  )
)
```



Spalte 2 {data-width=4}
----

###

```{r}
output$monthly_plot <- 
  renderPlot({
    data <- filtered_data()
    
    data |> 
      count(month, .data[[input$fill]]) |> 
      ggplot(
        aes(x = month, y = n)
      ) +
      geom_col(
        aes_string(fill =  input$fill)
      ) +
      theme(
        legend.position = "top",
        legend.title = element_blank(),
        axis.title = element_blank()
      )
  })

plotOutput("monthly_plot")
```

###

```{r}
output$weekday_plot <- 
  renderPlot({
    data <- filtered_data()
    
    data |> 
      count(weekday, .data[[input$fill]]) |> 
      ggplot(
        aes(x = weekday, y = n)
      ) +
      geom_col(
        aes_string(fill =  input$fill)
      ) +
      theme(
        legend.position = "top",
        legend.title = element_blank(),
        axis.title = element_blank()
      )
  })

plotOutput("weekday_plot")
```

###

```{r}
output$hourly_plot <- 
  renderPlot({
    data <- filtered_data()
    
    data |> 
      count(hour, .data[[input$fill]]) |> 
      ggplot(
        aes(x = hour, y = n)
      ) +
      geom_col(
        aes_string(fill =  input$fill)
      ) +
      theme(
        legend.position = "top",
        legend.title = element_blank(),
        axis.title = element_blank()
      )
  })

plotOutput("hourly_plot")
```


Stadtteile
====

Spalte 1
----

###

```{r}
# district data
filtered_districts <- reactive({
  res <- 
    filtered_data() |> 
    st_as_sf(coords = c("lng", "lat"), crs = "WGS84") |> 
    rename(
      points = geometry
    ) |> 
    st_join(
      y = sf.districts |> rename("district_shape" = geometry),
      join = st_within,
      left = TRUE
    ) |> 
    select(-m2) |> 
    as_tibble() |> 
    left_join(
      y = sf.districts |> rename("district_polygon" = geometry) ,
      by = "district"
    ) |>
    drop_na(district) |>
    mutate(
      district = as_factor(district) |>
        fct_infreq() |>
        fct_rev()
    ) |> 
    add_count(district) |> 
    select(district, district_polygon, n) |> 
    unique()
  
  if (input$selected_scale == "absolute") {
    res <- 
      res |> 
      st_as_sf()
  }
  
  if (input$selected_scale == "relative") {
    res <-
      res |> 
      mutate(
        n = n/max(res$n)
      ) |> 
      st_as_sf()
  }
  
  return(res)
})

labels <- function(data) {
  glue::glue(
    "{data$district}: {round(data$n, digits = 2)}"
  )
}


output$map2 <- 
  renderLeaflet({
    leaflet(
    data = filtered_data(),
    options = leafletOptions(
      crs = leafletCRS(code = "WGS84"),
      preferCanvas = NULL
    )
  ) |> 
  fitBounds(~min(lng), ~min(lat), ~max(lng), ~max(lat)) |> 
  setMaxBounds(~min(lng), ~min(lat), ~max(lng), ~max(lat)) |>
    addProviderTiles(
      provider = providers$Stamen.TonerBackground,
      group = "Stadtteile",
      options = providerTileOptions(minZoom = 11)
    ) |> 
    addPolygons(
      data = filtered_districts(),
      group = "Stadtteile",
      opacity = 1,
      weight = 0.5, 
      fillOpacity = 0.8,
      color = "black",
      fillColor = ~colorNumeric("viridis", n)(n),
      highlightOptions = highlightOptions(
        color = "white", 
        weight = 2,
        bringToFront = TRUE
      ),
      label = labels(filtered_districts())
    )
  })


leafletOutput("map2")
```

```{r}
absolutePanel(
  id = "controls2",
  class = "panel panel-default",
  fixed = TRUE,
  draggable = TRUE,
  top = 75,
  left = 290,
  right = "auto",
  bottom = "auto",
  width = 180,
  height = "auto",

  selectInput(
    inputId = "selected_scale",
    label = "",
    choices = c(
      "Absolut" = "absolute",
      "Relativ" = "relative"
    ), 
    selected = "Absolut"
  )
)
```

Spalte 2
----

### 

```{r}
output$district_plot <- renderPlot({
  filtered_districts() |>
    ggplot(aes(x = district, y = n)) +
    geom_bar(
      aes(fill = n),
      stat = "identity"
    ) +
    scale_fill_viridis() +
    theme(
      axis.title = element_blank(),
      legend.title = element_blank(),
      panel.background = element_blank()
    ) +
    coord_flip()
})

plotOutput("district_plot")
```

